### ISSUE TITLE
List tables

### ISSUE THREAD

**Issue by fierzdev** [oussjarrousse/pytest-minio-mock#12]
First of all, thanks for the package. 

While using it to write some testcases I discovered, that list_objects behaves differently than Minio.
Would you be interested in a PR that behaves more like Minio with respect to recursion and that returns something that has a object_name attribute instead of returning strings?

A small example for the recursion difference. Imaging having a bucket "bucket" with the following folders:
- a
- a - b 
- a - c
- a - c - d
- a - c - e

If we run `list_objects("bucket", "a")` this package returns `a - b`, `a-c-d`, `a-c-e.` In Minio it would return `a-b`, `a-c`. It would not go into the folder c, unless recursive is set.

**Comment by oussjarrousse** [comment]
Hello @fierzdev
Yes please go ahead and create a PR that fixes the issue. I highly value contributions.
I will also try to merge it and release a new version as soon as everything is in place.
Let me know if you need any help.
Thank you and Good Luck

**Comment by oussjarrousse** [comment]
Any progress or roadblocks?

**Comment by oussjarrousse** [comment]
Hello @fierzdev, I hope you are doing well. 
I am wondering if you have an idea on how to fix the code to fix the bug.
Or if you can write a test so that I can use to fix the bug, that would be wonderful.
Looking forward to hear from you

**Comment by oussjarrousse** [comment]
How about this as a solution for the recursion problem?

```
    def list_objects(self, bucket_name, prefix="", recursive=False, start_after=""):
        """
        Lists objects in a bucket with the specified prefix and conditions.

        Simulates listing objects in a bucket in the mock Minio server.

        Args:
            bucket_name (str): The name of the bucket to list objects from.
            prefix (str, optional): The prefix to filter objects by. Defaults to "".
            recursive (bool, optional): Whether to list objects recursively. Defaults to False.
            start_after (str, optional): The object name to start listing after. Defaults to "".

        Returns:
            list: A list of object names that match the specified conditions.
        """
        if bucket_name not in self.buckets:
            raise S3Error(
                message="bucket does not exist",
                resource=bucket_name,
                request_id=None,
                host_id=None,
                response="mocked_response",
                code=404,
                bucket_name=bucket_name,
                object_name=None,
            )
        bucket = self.buckets[bucket_name]
        bucket_objects = []
        if recursive is True:
            # If recursive, add all objects that match the prefix
            for obj_name in bucket:
                if obj_name.startswith(prefix) and (
                    start_after == "" or obj_name > start_after
                ):
                    # Here, just returning object name for simplicity
                    bucket_objects.append(obj_name)
        else:
            # If not recursive, add only direct children of the prefix
            for obj_name in bucket:
                if obj_name.startswith(prefix) and (
                    start_after == "" or obj_name > start_after
                ):
                    suffix = obj_name[len(prefix):].lstrip('/')
                    # If there's no slash in the remainder, it's a direct child
                    if '/' not in suffix:
                        bucket_objects.append(obj_name)
        
        return bucket_objects
```

**Comment by oussjarrousse** [comment]
And this to address both issues, the recursion and the .object_name issue

from collections import namedtuple

# Define a simple class or named tuple to hold object info
ObjectInfo = namedtuple("ObjectInfo", ["object_name"])

def list_objects(self, bucket_name, prefix="", recursive=False, start_after=""):
    if bucket_name not in self.buckets:
        raise S3Error(
            message="bucket does not exist",
            resource=bucket_name,
            request_id=None,
            host_id=None,
            response="mocked_response",
            code=404,
            bucket_name=bucket_name,
            object_name=None,
        )
    bucket = self.buckets[bucket_name]
    bucket_objects = []
    for obj_name in bucket:
        # Ensure the object matches the prefix and is after the start_after marker
        if obj_name.startswith(prefix) and (start_after == "" or obj_name > start_after):
            if recursive:
                # If recursive, add all objects that match the prefix
                bucket_objects.append(ObjectInfo(object_name=obj_name))
            else:
                # If not recursive, add only direct children of the prefix
                suffix = obj_name[len(prefix):].lstrip('/')
                # If there's no slash in the remainder, it's a direct child
                if '/' not in suffix:
                    bucket_objects.append(ObjectInfo(object_name=obj_name))
    return bucket_objects

**Comment by oussjarrousse** [comment]
this is the test:

```
@pytest.mark.REGRESSION
@pytest.mark.UNIT
@pytest.mark.API
def test_list_objects(minio_mock):
    client = Minio("http://local.host:9000")
    bucket_name = "new-bucket"
    client.make_bucket(bucket_name)
    objects = client.list_objects(bucket_name)
    assert len(objects) == 0
    with pytest.raises(S3Error):
        objects = client.list_objects("no-such-bucket")
        
    client.put_object(bucket_name, "a/b/c/object1", data=b"object1 data", length=12)
    client.put_object(bucket_name, "a/b/object2", data=b"object2 data", length=12)
    client.put_object(bucket_name, "a/object3", data=b"object3 data", length=11)
    client.put_object(bucket_name, "object4", data=b"object4 data", length=11)

    # Test recursive listing
    objects_recursive = client.list_objects(bucket_name, prefix="a/", recursive=True)
    assert len(objects_recursive) == 3, "Expected 3 objects under 'a/' with recursion"
    # Check that all expected paths are returned
    assert set(obj.object_name for obj in objects_recursive) == {"a/b/c/object1", "a/b/object2", "a/object3"}

    # Test non-recursive listing
    objects_non_recursive = client.list_objects(bucket_name, prefix="a/", recursive=False)
    assert len(objects_non_recursive) == 2, "Expected 1 object under 'a/' without recursion"
    # Check that the correct path is returned
    assert set(obj.object_name for obj in objects_non_recursive) == {"a/object3", "a/b/"}

    print(objects_non_recursive)

    # Test listing at the bucket root
    objects_root = client.list_objects(bucket_name, recursive=False)
    print(objects_root)
    assert len(objects_root) == 2, "Expected 2 objects at the root"
    # Check that the correct paths are returned
    assert set(obj.object_name for obj in objects_root) == {"a/", "object4"}
    ```
    
    Did I get it right?

**Comment by fierzdev** [comment]
Sorry, this lost a bit of priority internally. I had also already written some code, which works for our stuff, but no testcases yet for this repo. I will look into your code on the weekend and give you feedback. In the meantime I openend a draft PR with my changes: https://github.com/oussjarrousse/pytest-minio-mock/pull/14
But after a quick glance I think the changes are similar, and your PR seems more mature and I think you got it right.

**Comment by oussjarrousse** [comment]
I made some changes to my PR so that list_objects returns a generator of minio Objects. It's now merged.
I also pushed the new version 1.10 to [pypi.org](https://pypi.org/project/pytest-minio-mock/)
