### ISSUE TITLE
Support bucket versioning

### ISSUE THREAD

**Issue by cottephi** [oussjarrousse/pytest-minio-mock#16]
Hi guys,
Would it be possible to add support for bucket versioning ? I need to be able to do

```python
import pytest
from minio.commonconfig import ENABLED
from minio.versioningconfig import VersioningConfig


@pytest.fixture
def minio_bucket(minio_mock):
    minio_client = minio.Minio()
    minio_client.make_bucket("mybucket")
    minio_client.set_bucket_versioning("mybucket", VersioningConfig(ENABLED))
```

But for now, I get "AttributeError: 'MockMinioClient' object has no attribute 'set_bucket_versioning'"

Is it already a work in progress on your side ?

If not, I would be happy to contribute. In that case, feel free to give me some advice on how to do it.

**Comment by cottephi** [comment]
I actually created a local branch with this new feature, I would like to contribute, could you invite me on the project ?

**Comment by oussjarrousse** [comment]
Hello @cottephi,
Thank you for raising this issue. No it is not already WIP on our side. 
If you would like to contribute, follow the usual path:
- fork the repository
- create a feature branch
- push the branch to your forked repository
- from the forked repository, create a "pull request" to this project.
The details are in the README file, under contribution.

Looking forward for your pull request :-)

**Comment by cottephi** [comment]
I would happily contribute but I do not seem to be allowed to push a new branch... when I try a get a premission denied.

**Comment by oussjarrousse** [comment]
Are you pushing to this repository? I see where the confusion is...

To contribute to this repository, you don't push your changes directly to this repository, but you push them to your forked repository on github. You should first "fork" the repository and add it to your repositories...

Take a quick look at one of these short tutorials: 
- https://www.youtube.com/watch?v=nT8KGYVurIU
- this: https://www.youtube.com/watch?v=_NrSWLQsDL4

This is how almost all open-source projects works.

**Comment by oussjarrousse** [comment]
You need to start here:
<img width="1434" alt="Screenshot 2024-04-18 at 13 23 43" src="https://github.com/oussjarrousse/pytest-minio-mock/assets/1843808/02c131c1-6143-4ded-81c1-5081a186f3f8">

**Comment by cottephi** [comment]
Yeah ok, I'll do it that way then

**Comment by oussjarrousse** [comment]
@cottephi I ended up refactoring the package to support versioning. I used most of your code and comments. But I also made many changes.

Closing this issue

**Comment by cottephi** [comment]
I read your changes, much better than what I did, thank you.
