### ISSUE TITLE
Add stat_object method

### ISSUE THREAD

**Issue by ediboc** [oussjarrousse/pytest-minio-mock#21]
I am using pytest-minio-mock in a project where I need to delete a document but I need to return an error if the document does not exist and for that I use the "stat_object" function. Could this function be added? or how could I do the test?

**Comment by oussjarrousse** [comment]
Hello @ediboc. Yes, `stat_object` is not implemented yet. However, @cottephi was interested in adding it and I am looking forward for the PR. If I didn't receive a PR by the end of the week. I will start working on it myself or maybe you want to contribute?

**Comment by cottephi** [comment]
I implemented it in my forked repo, which I changed quite a lot in the mean time. I do not think you will like to review all the changes at once, I am not even sure you would want to have them. I suggest you look at what I did for stat_object, and cherry pick the code. It is line 257 in https://github.com/cottephi/pytest-minio-mock/blob/master/pytest_minio_mock/plugin.py

**Comment by ediboc** [comment]
In the end I did what you can see in the code below, so that it simulates an error in the event that the object is not in the bucket:

def stat_object_side_effect(bucket_name, object_name):  # noqa: ARG001
        if object_name == "missing_id":
            error_code = "NoSuchKey"
            error_message = "The specified key does not exist."
            raise S3Error(error_code, error_message, None, None, None, None)

minio_moc.stat_object = Mock(side_effect=stat_object_side_effect)

**Comment by oussjarrousse** [comment]
Ok I just finished implementing and adding tests for `stat_object()`
I am going to publish it later as soon as I am done testing

**Comment by oussjarrousse** [comment]
published.
