### ISSUE TITLE
MockMinioBucket on get_object KeyError should raise a code of "NoSuchKey" instead of 404.

### ISSUE THREAD

**Issue by KelvinHong** [oussjarrousse/pytest-minio-mock#33]
When `MockMinioClient.get_object()` couldn't find an object, it should raises an `S3Error as e` with its code being `e.code=="NoSuchKey"`. It calls the `MockMinioBucket.get_object()` method internally.

However in this line of code it raises 404 instead: 

https://github.com/oussjarrousse/pytest-minio-mock/blob/46227a31c485cfbb8d26367a8d5b20fad18e0e74/pytest_minio_mock/plugin.py#L496-L509

Solution: 

Let this raises `code="NoSuchKey"`, align feature with official minio-py.

Additional Context: 

I believe this change is very suitable, see the `MockMinioBucket.stat_object()` that is immediately below `get_object()`:

https://github.com/oussjarrousse/pytest-minio-mock/blob/46227a31c485cfbb8d26367a8d5b20fad18e0e74/pytest_minio_mock/plugin.py#L526-L560

It did correctly raises NoSuchKey.

I can create a pull request, please let me know if you agree on this change? Thanks!

**Comment by oussjarrousse** [comment]
Thanks for raising this issue. Would you like to submit a PR? 
If yes, just make sure you add a test for it or modify an existing test to assert this behavior.
If no, I will return to this on Saturday.

**Comment by KelvinHong** [comment]
I will submit a PR around these two days, will let you know when it is done!
